"""Golden corpus: the exact bytes the fe-worker ships for each case must not change.

Each ``cases/<name>.yaml`` is run against the fake gribjump (``polytope_mars.testing``) through the
streaming API (``b"".join(PolytopeMars.extract_stream(request))``) and compared byte for byte with:

* ``expected_fixed/<name>.covjson`` when the case lists ``fixes:`` (legacy defects this branch fixes,
  see CHANGES.md; generated by this branch and reviewed);
* otherwise ``expected/<name>.covjson``, the legacy oracle (polytope-python 2.1.20 + covjsonkit 0.2.26),
  which is never rewritten by this test.

The fake gribjump raises ``DataNotFound`` for a call that includes a missing field, like the remote
gribjump; ``test_golden_with_empty_results_for_missing_fields`` runs every case again with the fake
returning empty results instead (``missing_mode="empty"``): the bytes must be the same in both modes.

The buffered API the fe-worker can also call is ``json.dumps(PolytopeMars.extract(request))`` over the
same stream, pinned against it by
``tests/test_streaming.py::test_extract_equals_json_dumps_of_stream``.

Cases with ``expect_error`` assert the exception instead.  After a deliberate output change of a fixed
case: ``pytest tests/golden --golden-regen`` (or ``GOLDEN_REGEN=1``) rewrites ``expected_fixed/`` only.
"""

import builtins
import re
from pathlib import Path

import pytest

from polytope_mars.testing.golden import (
    build_fake,
    load_case,
    run_case_stream,
)

HERE = Path(__file__).parent
CASES = sorted((HERE / "cases").glob("*.yaml"))


def _first_difference(actual: bytes, expected: bytes) -> str:
    n = next((i for i, (a, b) in enumerate(zip(actual, expected)) if a != b), min(len(actual), len(expected)))
    lo = max(0, n - 80)
    return (
        f"lengths actual={len(actual)} expected={len(expected)}; first difference at byte {n}\n"
        f"  actual:   ...{actual[lo:n + 80]!r}\n"
        f"  expected: ...{expected[lo:n + 80]!r}"
    )


def expected_path(case_path, case) -> Path:
    folder = "expected_fixed" if case.get("fixes") else "expected"
    return HERE / folder / f"{case_path.stem}.covjson"


@pytest.mark.parametrize("case_path", CASES, ids=[p.stem for p in CASES])
def test_golden(case_path, golden_regen):
    case = load_case(case_path)
    run = run_case_stream
    path = expected_path(case_path, case)

    if "expect_error" in case:
        err = case["expect_error"]
        exc_type = getattr(builtins, err["type"])
        with pytest.raises(exc_type, match=re.escape(err.get("match", ""))):
            run(case)
        assert not path.exists(), f"{path.name} exists for a case that expects an error"
        return

    actual = run(case)
    if golden_regen and case.get("fixes"):
        path.parent.mkdir(exist_ok=True)
        path.write_bytes(actual)
        return
    assert path.exists(), f"missing {path}" + ("; run with --golden-regen to create it" if case.get("fixes") else "")
    expected = path.read_bytes()
    assert actual == expected, _first_difference(actual, expected)


@pytest.mark.parametrize("case_path", [p for p in CASES if "expect_error" not in load_case(p)], ids=lambda p: p.stem)
def test_golden_with_empty_results_for_missing_fields(case_path):
    """The DataNotFound fallbacks reproduce exactly what empty gribjump results give."""
    case = load_case(case_path)
    actual = run_case_stream(case, build_fake(case, missing_mode="empty"))
    expected = expected_path(case_path, case).read_bytes()
    assert actual == expected, _first_difference(actual, expected)


@pytest.mark.parametrize("case_path", [p for p in CASES if load_case(p).get("fixes")], ids=lambda p: p.stem)
def test_fixed_cases_differ_from_oracle(case_path):
    """A case listed as fixed must really differ from the legacy bytes (or legacy must have raised)."""
    oracle = HERE / "expected" / f"{case_path.stem}.covjson"
    fixed = HERE / "expected_fixed" / f"{case_path.stem}.covjson"
    if not oracle.exists():
        assert "legacy_error" in load_case(case_path), "fixed case without oracle bytes must record legacy_error"
        return
    assert fixed.exists() and fixed.read_bytes() != oracle.read_bytes()
